# Generated by Django 6.0.4 on 2026-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='student_documents/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('head_teacher', 'Head Teacher'), ('senior_teacher', 'Senior Teacher'), ('teacher', 'Teacher'), ('assistant_teacher', 'Assistant Teacher')], default='teacher', max_length=100),
        ),
    ]
